package com.cloud.model.user;/*
 * Welcome to use the TableGo Tools.
 * 
 * http://www.tablego.cn
 * 
 * http://vipbooks.iteye.com
 * http://blog.csdn.net/vipbooks
 * http://www.cnblogs.com/vipbooks
 * 
 * Author: bianj
 * Email: tablego@qq.com
 * Version: 6.6.6
 */
import lombok.Data;

import java.sql.Timestamp;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 用户表(app_user)
 * 
 * @author jiangwenjie
 * @version 1.0.0 2020-03-10
 */
@Data
@Entity
@Table(name = "app_user")
public class AppUser implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 2310389584353685651L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false, length = 19)
    private Long id;

    /** 手机号 */
    @Column(name = "phone", unique = true, nullable = true, length = 13)
    private String phone;

    /** 用户名称 */
    @Column(name = "username", nullable = true, length = 40)
    private String username;

    /** 昵称 */
    @Column(name = "nickname", nullable = true, length = 40)
    private String nickname;

    /** 密码 */
    @Column(name = "password", nullable = true, length = 50)
    private String password;

    /** 头像小图url */
    @Column(name = "face_image", nullable = true, length = 300)
    private String faceImage;

    /** 头像原图url */
    @Column(name = "face_image_big", nullable = true, length = 300)
    private String faceImageBig;

    /** 二维码 */
    @Column(name = "qrcode", nullable = true, length = 300)
    private String qrcode;

    /** 终端设备id */
    @Column(name = "mac_id", nullable = true, length = 50)
    private String macId;

    /** 状态 1表示有效 0 表示无效 */
    @Column(name = "status", nullable = true, length = 10)
    private Integer status=1;

    /** 创建时间 */
    @Column(name = "create_time", nullable = true, length = 19)
    private Timestamp createTime;

    /** 修改时间 */
    @Column(name = "update_time", nullable = true, length = 19)
    private Timestamp updateTime;


}