package com.cloud.model.user;/*
 * Welcome to use the TableGo Tools.
 * 
 * http://www.tablego.cn
 * 
 * http://vipbooks.iteye.com
 * http://blog.csdn.net/vipbooks
 * http://www.cnblogs.com/vipbooks
 * 
 * Author: bianj
 * Email: tablego@qq.com
 * Version: 6.6.6
 */
import lombok.Data;

import java.sql.Timestamp;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 系统用户凭证表(sys_user_credentials)
 * 
 * @author jiangwenjie
 * @version 1.0.0 2020-03-05
 */
@Data
@Entity
@Table(name = "sys_user_credentials")
public class SysUserCredentials implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -1854880517337040053L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false, length = 19)
    private Long id;

    /** 登录类型 1用户名登录 2手机号登录 3微信登录 4支付宝登录 等等 */
    @Column(name = "login_type", nullable = true, length = 10)
    private Integer loginType;

    /** 账号 根据上面账号类型不同存入的值不同 */
    @Column(name = "login_account", unique = true, nullable = true, length = 60)
    private String loginAccount;

    /** 用户id */
    @Column(name = "sys_user_id", nullable = true, length = 19)
    private Long sysUserId;

    /** 创建时间 */
    @Column(name = "create_time", nullable = true, length = 19)
    private Timestamp createTime;


}