package com.cloud.model.user;/*
 * Welcome to use the TableGo Tools.
 * 
 * http://www.tablego.cn
 * 
 * http://vipbooks.iteye.com
 * http://blog.csdn.net/vipbooks
 * http://www.cnblogs.com/vipbooks
 * 
 * Author: bianj
 * Email: tablego@qq.com
 * Version: 6.6.6
 */
import lombok.Data;

import java.sql.Timestamp;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 用户好友关系表(user_friend)
 * 
 * @author jiangwenjie
 * @version 1.0.0 2020-03-10
 */
@Data
@Entity
@Table(name = "user_friend")
public class UserFriend implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 2197050044464377150L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false, length = 19)
    private Long id;

    /** 用户id */
    @Column(name = "user_id", nullable = true, length = 19)
    private Long userId;

    /** 好友id */
    @Column(name = "friend_user_id", nullable = true, length = 19)
    private Long friendUserId;

    /** 备注 */
    @Column(name = "remake", nullable = true, length = 30)
    private String remake;

    /** 创建时间 */
    @Column(name = "create_time", nullable = true, length = 19)
    private Timestamp createTime;

    /** 修改时间 */
    @Column(name = "update_time", nullable = true, length = 19)
    private Timestamp updateTime;

}