package com.cloud.model.log;/*
 * Welcome to use the TableGo Tools.
 * 
 * http://www.tablego.cn
 * 
 * http://vipbooks.iteye.com
 * http://blog.csdn.net/vipbooks
 * http://www.cnblogs.com/vipbooks
 * 
 * Author: bianj
 * Email: tablego@qq.com
 * Version: 6.6.6
 */
import lombok.Data;

import java.sql.Timestamp;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 系统日志表(sys_log)
 * 
 * @author jiangwenjie
 * @version 1.0.0 2020-03-05
 */
@Data
@Entity
@Table(name = "sys_log")
public class SysLog implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = 4889065319191993192L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false, length = 19)
    private Long id;

    /** 用户名称 */
    @Column(name = "username", nullable = true, length = 100)
    private String username;

    /** 操作名称 */
    @Column(name = "do_name", nullable = true, length = 120)
    private String doName;

    /** 方法参数 */
    @Column(name = "params", nullable = true, length = 1000)
    private String params;

    /** 备注 */
    @Column(name = "remark", nullable = true, length = 1000)
    private String remark;

    /** 是否成功 1表示成功 0表示失败 */
    @Column(name = "flag", nullable = true, length = 10)
    private Integer flag;

    /** 创建时间 */
    @Column(name = "create_time", nullable = true, length = 19)
    private Timestamp createTime;


}