logging:
  level:
    root: info
    com.cloud: debug
  file: logs/${spring.application.name}.log
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.79.157.199:3306/cloud_user?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 8251314926
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  rabbitmq:
    host: 192.168.1.105
    port: 5672
    username: cloud-dev
    password: cloud-dev
    virtual-host: /

  redis:
    host: 120.79.157.199
    port: 6379
    password: 740498523
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  mvc:
    servlet:
      load-on-startup: 1
  aop:
    proxy-target-class: true

mybatis:
  type-aliases-package: com.cloud.model
  mapper-locations: classpath:/mybatis-mappers/*
  configuration:
    mapUnderscoreToCamelCase: true

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

#websocket连接地址端口配置
#netty-websocket.host=0.0.0.0
netty-websocket:
  path: /ws/user/message #连接地址
  port: 9999  #netty 端口号

channel:
  im:
    name: imChannel  #redis订阅的频道名称