package com.cloud.model.message;/*
 * Welcome to use the TableGo Tools.
 * 
 * http://www.tablego.cn
 * 
 * http://vipbooks.iteye.com
 * http://blog.csdn.net/vipbooks
 * http://www.cnblogs.com/vipbooks
 * 
 * Author: bianj
 * Email: tablego@qq.com
 * Version: 6.6.6
 */
import lombok.Data;

import java.sql.Timestamp;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 聊天消息记录表(chat_msg)
 * 
 * @author jiangwenjie
 * @version 1.0.0 2020-03-10
 */
@Data
@Entity
@Table(name = "chat_msg")
public class ChatMsg implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -7305012898530460451L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false, length = 19)
    private Long id;

    /** 发送方id */
    @Column(name = "send_user_id", nullable = true, length = 19)
    private Long sendUserId;

    /** 接收方id */
    @Column(name = "accept_user_id", nullable = true, length = 19)
    private Long acceptUserId;

    /** 消息内容 */
    @Column(name = "content", nullable = true, length = 1000)
    private String content;

    /** 发送类型 1点对点发送 2消息群发 */
    @Column(name = "send_type", nullable = true, length = 10)
    private Integer sendType;

    /** 消息类型 1文字 2语音 3图片等等 */
    @Column(name = "msg_type", nullable = true, length = 10)
    private Integer msgType;

    /** 消息是否签收 0没有签收 1签收 */
    @Column(name = "sign_flag", nullable = true, length = 10)
    private Integer signFlag=0;

    /** 签收时间 */
    @Column(name = "sign_time", nullable = true, length = 19)
    private Timestamp signTime;

    /** 创建时间 */
    @Column(name = "create_time", nullable = true, length = 19)
    private Timestamp createTime;


}