package com.cloud.model.user;/*
 * Welcome to use the TableGo Tools.
 * 
 * http://www.tablego.cn
 * 
 * http://vipbooks.iteye.com
 * http://blog.csdn.net/vipbooks
 * http://www.cnblogs.com/vipbooks
 * 
 * Author: bianj
 * Email: tablego@qq.com
 * Version: 6.6.6
 */
import lombok.Data;

import java.sql.Timestamp;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 好友请求表(friend_request)
 * 
 * @author jiangwenjie
 * @version 1.0.0 2020-03-10
 */
@Data
@Entity
@Table(name = "friend_request")
public class FriendRequest implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -5627030519652985661L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false, length = 19)
    private Long id;

    /** 发送方id */
    @Column(name = "send_user_id", nullable = true, length = 19)
    private Long sendUserId;

    /** 接收方id */
    @Column(name = "accept_user_id", nullable = true, length = 19)
    private Long acceptUserId;

    /** 创建时间 */
    @Column(name = "create_time", nullable = true, length = 19)
    private Timestamp createTime;


}