package com.cloud.model.user;/*
 * Welcome to use the TableGo Tools.
 * 
 * http://www.tablego.cn
 * 
 * http://vipbooks.iteye.com
 * http://blog.csdn.net/vipbooks
 * http://www.cnblogs.com/vipbooks
 * 
 * Author: bianj
 * Email: tablego@qq.com
 * Version: 6.6.6
 */
import lombok.Data;

import java.sql.Timestamp;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * 后台管理用户表(sys_user)
 * 
 * @author jiangwenjie
 * @version 1.0.0 2020-03-05
 */
@Data
@Entity
@Table(name = "sys_user")
public class SysUser implements java.io.Serializable {
    /** 版本号 */
    private static final long serialVersionUID = -6762048925259448863L;

    /* This code was generated by TableGo tools, mark 1 begin. */

    /** id */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false, length = 19)
    private Long id;

    /** 用户名称 */
    @Column(name = "username", unique = true, nullable = true, length = 60)
    private String username;

    /** 密码 */
    @Column(name = "password", nullable = true, length = 60)
    private String password;

    /** 昵称 */
    @Column(name = "nickname", nullable = true, length = 60)
    private String nickname;

    /** 头像 */
    @Column(name = "head_img_url", nullable = true, length = 400)
    private String headImgUrl;

    /** 手机号 */
    @Column(name = "phone", unique = true, nullable = true, length = 15)
    private String phone;

    /** 状态 1表示有效 0 表示无效 */
    @Column(name = "status", nullable = true, length = 10)
    private Integer status;

    /** 创建时间 */
    @Column(name = "create_time", nullable = true, length = 19)
    private Timestamp createTime;

    /** 修改时间 */
    @Column(name = "update_time", nullable = true, length = 19)
    private Timestamp updateTime;


}